### ISSUE TITLE
怎么配置前端连接后端服务容器

### ISSUE THREAD

**Issue by Ghost-Cavendish** [ciliverse/cilikube#82]
无法连接到后端服务 (http://127.0.0.1:8080)，请确保后端服务正在运行并检查网络连接。

networks:
  1panel-network:
    external: true
services:
  backend:
    image: cilliantech/cilikube:v0.1.0
    container_name: cilikube-server
    restart: unless-stopped
    networks:
      - 1panel-network
  frontend:
    image: cilliantech/cilikube-web:v0.1.0  
    container_name: cilikube-web
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - 1panel-network

**Comment by fxkjnj** [comment]
官方的docker-compose.yaml 中有说明，需要自己正确配置 前端 VITE_BASE_API 地址，默认的镜像地址的后端地址是.env 中的 VITE_API_BASE_URL = http://127.0.0.1:8080

所以你需要：

1. 修改前端代码的.env 配置文件，比如定义成 /api 的方式 ；
```
# 所有环境自定义的环境变量（命名必须以 VITE_ 开头）

## 项目标题
VITE_APP_TITLE = cilikube

VITE_API_BASE_URL = /api

```

2. 添加一个nginx.conf 的配置文件，使用nginx代理的方式，访问后端接口

```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
    location /api/ {
        # 动态路径代理设置
		proxy_pass http://backend:8080/;
        # 保持原始请求路径（自动去掉/api前缀）
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

3.修改Dockerfile 文件，打开nginx.conf 配置文件注释的那一行
```
# 使用最新 LTS 版本的 Node.js 作为构建基础镜像，并命名为 builder
FROM node:lts AS builder

# 设置工作目录为 /app
WORKDIR /app

# 复制 package.json 和 pnpm-lock.yaml（如果使用 pnpm，同时支持 npm）
COPY package.json pnpm-lock.yaml* ./

# 安装项目依赖
RUN npm install -g pnpm && \
    pnpm install --frozen-lockfile # 确保依赖版本一致

# 复制项目源代码到工作目录
COPY . .

# 运行构建命令
RUN pnpm build

# --- 生产环境镜像 ---
# 使用 Alpine 版本的 Nginx 作为基础镜像，以减小体积
FROM nginx:stable-alpine

# 从 builder 阶段复制构建产物到 Nginx 的默认静态资源目录
COPY --from=builder /app/dist /usr/share/nginx/html

# （可选）如果您有自定义的 Nginx 配置，取消注释并复制
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 暴露 80 端口，允许外部访问
EXPOSE 80

# 启动 Nginx 服务，并保持在前台运行
CMD ["nginx", "-g", "daemon off;"]

```


4. 构建你的前端镜像
```
docker build -t XXX:XXX .
```
> 也可以使用我构建好的镜像： `docker.cnb.cool/sre/custom-vscode/cilikube-web`

5.修改docker-compose文件，只需要修改image 镜像地址修改成自己构建的地址即可
```
services:
  backend:
    image: cilliantech/cilikube:v0.1.0
    container_name: cilikube-server
    ports:
      - "8080:8080" # 宿主机端口:容器内应用端口
    restart: unless-stopped
    # 如果后端应用依赖其他服务 (如数据库)，可以在这里添加 depends_on 和 network 配置

  frontend:
    image: docker.cnb.cool/sre/custom-vscode/cilikube-web   #可使用我构建的镜像😄
    container_name: cilikube-web
    ports:
      - "80:80" # 宿主机端口:容器内 Nginx 端口 (通常是80)
                # 如果宿主机 80 端口被占用，可改为 "8000:80"
    restart: unless-stopped
    depends_on:
      - backend # 确保后端先启动 (但不保证后端已完全就绪)
    # 注意：前端 VITE_BASE_API 在构建镜像时仍需正确配置，
    # 例如指向 http://localhost:8080 (如果从浏览器访问)
    # 或 http://backend:8080 (如果Nginx配置了反向代理到服务名'backend'，这需要更复杂的Nginx配置)

# (可选) 定义网络，如果服务间需要通过服务名通信
# networks:
#   cilikube-net:
#     driver: bridge
```

5.docker-compose 一键运行
```
docker-compose up -d
```

6. 效果
![](https://s3api.srebro.cn:443/picgo/202505111201555.png)


最后希望能帮助到你😄
